version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  target-branch: "master"
  open-pull-requests-limit: 10
  reviewers:
  - yushan87
  labels:
  - dependencies
