#
# Continuous integration settings for Travis CI
#
dist: trusty
sudo: false
branches:
  only:
    - master

# Jekyll TravisCI settings
# See: https://jekyllrb.com/docs/continuous-integration/travis-ci/ for more information.
language: ruby
rvm:
  - 2.4.1 # Latest Ruby version in TravisCI
  - 2.5.1 # Latest Ruby version

install: gem install jekyll bundler html-proofer

script: jekyll build && htmlproofer ./_site --disable-external

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache: bundler # caching bundler gem packages will speed up build