#
# Continuous integration settings for Travis CI
#
dist: trusty
branches:
  only:
    - master

# Jekyll TravisCI settings
# See: https://jekyllrb.com/docs/continuous-integration/travis-ci/ for more information.
language: ruby
rvm:
  - 2.4.1 # Latest Ruby version in TravisCI
  - 2.6.4 # Latest Ruby version

before_script:
  - gem update --system
  - gem --version
  - gem install bundler:2.0.2
  - bundle update --bundler

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --disable-external --assume-extension

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache: bundler # caching bundler gem packages will speed up build
