# Jekyll configuration

title: RESOLVE Tutorial
email: clemsonrsrg@gmail.com

baseurl: "/tutorial" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: ClemsonRSRG
github_label: git

googleplus_username: "113522124528253946818"
googleplus_label: google+

# Build settings
markdown: kramdown
#plugins:

encoding: utf-8

collections_dir: lessons
collections: 
  main:
    output: true
    permalink: /:collection/:path

defaults:
  - scope:
      path: ""
      type: main
    values:
      layout: tutorial

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - README.md
