# This workflow will download a prebuilt Ruby version, install dependencies, attempt to build 
# and run the HTML Proofer.
# For more information see: https://github.com/ruby/setup-ruby

name: RESOLVETutorial (Ruby + Jekyll)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        ruby-version: [ '3.2', '3.3', '3.4' ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Build
      run: bundle exec jekyll build
    - name: HTML Validator and Proofer
      uses: anishathalye/proof-html@v2
      with:
        directory: ./_site
        enforce_https: false
        check_favicon: false
        ignore_url: |
          https://begintoreason.cs.clemson.edu